"""add snapshot timestamp

Revision ID: b315918d858a
Revises: 35d5f05dc2b2
Create Date: 2022-11-02 22:02:47.149920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b315918d858a'
down_revision = '35d5f05dc2b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_record', sa.Column('timestamp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot_record', 'timestamp')
    # ### end Alembic commands ###
